INSERT INTO
    recipes_recipe (
        name,
        detail,
        date_created,
        updated,
        category,
        image,
        created_by_id
    )
VALUES
    (
        'Creamy Garlic Shrimp',
        'This dish is rich, creamy, andd with garlic flavor. The shrimp is cooked in a creamy sauce and served over pasta for a ying and delicious meal.',
        '2023-03-24 17:49:27.395710',
        '2023-03-24 17:49:27.396706',
        'e',
        'images/shrimp-ceviche_3.webp',
        3
    );