# Generated by Django 4.1.7 on 2023-03-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("detail", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("desserts", "D"),
                            ("entrees", "E"),
                            ("appetizers", "A"),
                        ],
                        default="appetizers",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
